// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Swr from "swr";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Router from "next/router";

function $$default(param) {
  var router = Router.useRouter();
  var match = React.useState(function () {
        return false;
      });
  var setAgree = match[1];
  var agree = match[0];
  var match$1 = React.useState(function () {
        return "";
      });
  var setName = match$1[1];
  var name = match$1[0];
  var match$2 = React.useState(function () {
        return "";
      });
  var setPhoneNumber = match$2[1];
  var phoneNumber = match$2[0];
  var validCheck = function (name, phoneNumber, agree) {
    var name_b = name.length > 1;
    var phoneNumber_b = phoneNumber !== "";
    return !(name_b && phoneNumber_b && agree);
  };
  var checkedPrivacy = function (e) {
    var value = e.currentTarget.checked;
    return Curry._1(setAgree, (function (param) {
                  return value;
                }));
  };
  var handleNameChange = function (e) {
    var value = e.currentTarget.value;
    return Curry._1(setName, (function (param) {
                  return value;
                }));
  };
  var handlePhoneNumberChange = function (e) {
    var value = e.currentTarget.value;
    return Curry._1(setPhoneNumber, (function (param) {
                  return value;
                }));
  };
  var handleClick = function (param) {
    router.push("/step2");
    
  };
  var globalConfig = Swr.useSWRConfig();
  var refreshInterval = globalConfig.refreshInterval;
  console.log(refreshInterval === undefined ? undefined : Caml_option.some(refreshInterval));
  return React.createElement("div", {
              className: "h-screen pt-14 relative"
            }, React.createElement("div", {
                  className: "relative"
                }, React.createElement("div", {
                      className: "absolute w-full"
                    }, React.createElement("div", {
                          className: "flex w-full"
                        }, React.createElement("div", {
                              className: "flex-1 h-0.5 bg-green-700"
                            }), React.createElement("div", {
                              className: "flex-1 h-0.5 bg-gray-100"
                            }), React.createElement("div", {
                              className: "flex-1 h-0.5 bg-gray-100"
                            }), React.createElement("div", {
                              className: "flex-1 h-0.5 bg-gray-100"
                            }), React.createElement("div", {
                              className: "flex-1 h-0.5 bg-gray-100"
                            }), React.createElement("div", {
                              className: "flex-1 h-0.5 bg-gray-100"
                            }), React.createElement("div", {
                              className: "flex-1 h-0.5 bg-gray-100"
                            }), React.createElement("div", {
                              className: "flex-1 h-0.5 bg-gray-100"
                            }), React.createElement("div", {
                              className: "flex-1 h-0.5 bg-gray-100"
                            }), React.createElement("div", {
                              className: "flex-1 h-0.5 bg-gray-100"
                            }))), React.createElement("div", {
                      className: "mx-5"
                    }, React.createElement("h1", {
                          className: "font-bold text-2xl pt-14"
                        }, "정확한 시공 견적을 위해", React.createElement("br", undefined), React.createElement("span", {
                              className: "text-green-500"
                            }, "이름"), "과 ", React.createElement("span", {
                              className: "text-green-500"
                            }, "휴대전화번호"), "를", React.createElement("br", undefined), "알려주세요"), React.createElement("form", {
                          className: "mt-12"
                        }, React.createElement("div", {
                              className: "mb-5"
                            }, React.createElement("input", {
                                  className: "form-input w-full border-gray-300 border-solid rounded-md border-2",
                                  placeholder: "이름을 입력해 주세요",
                                  value: name,
                                  onChange: handleNameChange
                                })), React.createElement("div", undefined, React.createElement("input", {
                                  className: "form-input w-full border-gray-300 border-solid rounded-md border-2",
                                  placeholder: "휴대전화번호를 입력해 주세요",
                                  value: phoneNumber,
                                  onChange: handlePhoneNumberChange
                                })), React.createElement("div", {
                              className: "mt-7"
                            }, React.createElement("label", {
                                  className: "flex items-center"
                                }, React.createElement("input", {
                                      checked: agree,
                                      type: "checkbox",
                                      onChange: checkedPrivacy
                                    }), React.createElement("span", {
                                      className: "ml-2"
                                    }, "(필수)개인정보 수집·이용제공·마케팅 활용에 동의합니다.")))))), React.createElement("div", {
                  className: "fixed text-center bottom-0 w-full"
                }, React.createElement("div", {
                      className: "min-w-max max-w-2xl p-5"
                    }, React.createElement("button", {
                          className: "w-full disabled:bg-gray-300 disabled:text-white disabled:opacity-50 bg-green-700 text-white border border-solid border-transparent rounded-xl",
                          disabled: validCheck(name, phoneNumber, agree),
                          onClick: handleClick
                        }, React.createElement("span", {
                              className: "text-lg leading-10"
                            }, "다음")))));
}

var Router$1;

export {
  Router$1 as Router,
  $$default ,
  $$default as default,
  
}
/* swr Not a pure module */
