// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Step2$Step2(Props) {
  return React.createElement("div", undefined, React.createElement("div", {
                  className: "absolute left-0"
                }, React.createElement("div", {
                      className: "cursor-pointer w-14 h-14 p-3"
                    }, React.createElement("svg", {
                          fill: "none",
                          stroke: "currentColor",
                          viewBox: "0 0 24 24",
                          xmlns: "http://www.w3.org/2000/svg"
                        }, React.createElement("path", {
                              d: "M15 19l-7-7 7-7",
                              strokeLinecap: "round",
                              strokeLinejoin: "round",
                              strokeWidth: "2"
                            })))), React.createElement("div", {
                  className: "pt-14 relative"
                }, React.createElement("div", {
                      className: "flex w-full"
                    }, React.createElement("div", {
                          className: "flex-1 h-0.5 bg-green-700"
                        }), React.createElement("div", {
                          className: "flex-1 h-0.5 bg-gray-100"
                        }), React.createElement("div", {
                          className: "flex-1 h-0.5 bg-gray-100"
                        }), React.createElement("div", {
                          className: "flex-1 h-0.5 bg-gray-100"
                        }), React.createElement("div", {
                          className: "flex-1 h-0.5 bg-gray-100"
                        }))), React.createElement("div", {
                  className: "mx-5"
                }, React.createElement("h1", {
                      className: "font-bold text-2xl pt-14"
                    }, React.createElement("span", {
                          className: "text-green-500"
                        }, "어떤 유형"), "의", React.createElement("br", undefined), "하우스 시공을 원하시나요?")));
}

var Step2 = {
  make: Step2$Step2
};

function $$default(param) {
  return React.createElement(Step2$Step2, {});
}

export {
  Step2 ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
