// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Test$Profile(Props) {
  var name = Props.name;
  var imageUrl = Props.imageUrl;
  return React.createElement("img", {
              className: "avatar",
              alt: name,
              src: imageUrl
            });
}

var Profile = {
  make: Test$Profile
};

function $$default(param) {
  return React.createElement("section", undefined, React.createElement("h1", {
                  className: "text-6xl"
                }, "Amazing scientists"), React.createElement(Test$Profile, {
                  name: "Lin Lanying",
                  imageUrl: "https://i.imgur.com/1bX5QH6.jpg"
                }), React.createElement(Test$Profile, {
                  name: "Gregorio Y. Zara",
                  imageUrl: "https://i.imgur.com/7vQD0fPs.jpg"
                }), React.createElement(Test$Profile, {
                  name: "Hedy Lamarr",
                  imageUrl: "https://i.imgur.com/yXOvdOSs.jpg"
                }));
}

export {
  Profile ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
