// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function SimEstLayout(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: "flex flex-row justify-center"
            }, React.createElement("div", {
                  className: "w-full"
                }, React.createElement("div", {
                      className: "max-w-2xl m-auto flex-col relative"
                    }, children)));
}

var make = SimEstLayout;

export {
  make ,
  
}
/* react Not a pure module */
